FROM php:8.2-apache

# Instalar dependencias y extensiones de PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Habilitar módulos de Apache si lo necesitas
RUN a2enmod rewrite
